config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :positions, except: [:show] do
    put :toggle, on: :member
  end
  resources :departments, except: [:show] do
    put :toggle, on: :member
  end
  resources :phones, except: [:show] do
    put :toggle, on: :member
  end
  resources :phonebooks, only: [:index]
  resources :patients, except: [:show, :destroy] do
    put :toggle, on: :member
  end
  get 'my_patients', to: 'patients#my_patients'
  get 'my_patients/:patient_id/testing', to: 'testings#go_to_test', as: 'go_to_testings'
  get 'my_patients/:patient_id/testing/history', to: 'testings#history', as: 'history_testings'
  get 'my_patients/:patient_id/testing/:test_id/new', to: 'testings#new', as: 'new_testings'
  post 'my_patients/:patient_id/testing', to: 'testings#create', as: 'testings'

  get 'my_patients/:patient_id/medical_records', to: 'medical_records#index', as: 'medical_records'
  get 'my_patients/:patient_id/medical_records/new', to: 'medical_records#new', as: 'new_medical_records'
  post 'my_patients/:patient_id/medical_records', to: 'medical_records#create', as: 'medical_record'

  resources :vacations, except: [:show]
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id         :integer          not null, primary key
#  level      :integer
#  lock       :boolean          default(FALSE)
#  name       :string           default("")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Position < ApplicationRecord
  include Defaultable
  include Activeable
  include Sortable
  include Toggleable
  include Statusable

  has_many :users

  validates :level, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_hr

  def index
    @positions = Position.all.order_by(:level)
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new position_params
    if @position.save
      redirect_to positions_path, notice: "Добавлена должжность #{@position.name}"
    else
      redirect_to positions_path, alert: "Ошибка при добавлении должность #{@position.name}"
    end
  end

  def edit
    @position = Position.find(params[:id])
  end

  def update
    @position = Position.find(params[:id])
    if @position.update position_params
      flash[:notice] = "Обновлена должность #{@position.name}"
    else
      flash[:alert] = "Ошибка при обновлений должности #{@position.name}"
    end
    redirect_to positions_path
  end

  def destroy
    @position = Position.find(params[:id])
    if @position.delete
      redirect_to positions_path, notice: "Удалена должность #{@position.name}"
    else
      redirect_to positions_path, alert: "Ошибка при удалении должности #{@position.name}"
    end
  end

  def toggle
    @position = Position.find(params[:id])
    if @position.toggle!
      flash[:notice] = "Обновлен статус #{@position.name}"
    else
      flash[:alert] = "Ошибка при обновлении статуса #{@position.name}"
    end
    redirect_to positions_path
  end

  private

  def position_params
    params.require(:position).permit(:name, :level, :lock)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.slim
= form_with(model: position) do |form|
  .input-group
    = form.label :level, class: 'label'
    = form.text_field :level, class: 'input', id: 'position-level'
  .input-group
    = form.label :name
    = form.text_field :name, class: 'input', id: 'position-name'  
  .mb-6.input-checkbox
    = form.check_box :lock
    = form.label :lock, class:"label"
  .input-group
    = form.submit class: 'btn btn-default', id: 'position-submit'

app/views/positions/_position.slim
tr class=("row #{position.lock ? 'disable' : ''}")
  td.row-item
    .flex.items-center= index + 1
  td.row-item
    .flex.items-center
      .ml-4
        .text-sm.font-medium.text-gray-900
          = position.level
  td.row-item
    .text-sm.text-gray-900= position.name
  td.row-item
    span.px-2.inline-flex.text-xs.leading-5.font-semibold.rounded-full.bg-green-100.text-green-800
      = position.status
  td.row-item.text-right.text-sm.font-medium
    = link_to toggle_position_path(position), method: :put, class: 'btn btn-green btn-outline mr-2', id: "position-toggle-#{position.id}" do
      i.fas.fa-toggle-on titile="Поменять статус"
    = link_to edit_position_path(position), class: 'btn btn-indigo btn-outline mr-2' do
      i.far.fa-edit title="Редактировать"
    = link_to position_path(position), method: :delete, class: 'btn btn-red btn-outline', id: "position-destroy-#{position.id}" do
      i.fas.fa-trash title="Удалить"

app/views/positions/edit.slim
.mt-8
  =render 'positions/form', position: @position

app/views/positions/index.slim
h1.text-center Отделы
.flex.flex-col.text-left.mt-10
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.table
          thead.head
            tr
              th.column scope="col" 
                | №
              th.column scope="col" 
                | Уровень
              th.column scope="col" 
                | Название
              th.column scope="col" 
                | Стаутс
              th.relative.px-6.py-3 scope="col" 
                span.sr-only Edit
          tbody.bg-white.divide-y.divide-gray-200
            - @positions.each_with_index do |position, index|
              = render 'positions/position', position: position, index: index

app/views/positions/new.slim
.mt-8
  =render 'positions/form', position: @position