config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :positions, except: [:show] do
    put :toggle, on: :member
  end
  resources :departments, except: [:show] do
    put :toggle, on: :member
  end
  resources :phones, except: [:show] do
    put :toggle, on: :member
  end
  resources :phonebooks, only: [:index]
  resources :patients, except: [:show, :destroy] do
    put :toggle, on: :member
  end
  get 'my_patients', to: 'patients#my_patients'
  get 'my_patients/:patient_id/testing', to: 'testings#go_to_test', as: 'go_to_testings'
  get 'my_patients/:patient_id/testing/history', to: 'testings#history', as: 'history_testings'
  get 'my_patients/:patient_id/testing/:test_id/new', to: 'testings#new', as: 'new_testings'
  post 'my_patients/:patient_id/testing', to: 'testings#create', as: 'testings'

  get 'my_patients/:patient_id/medical_records', to: 'medical_records#index', as: 'medical_records'
  get 'my_patients/:patient_id/medical_records/new', to: 'medical_records#new', as: 'new_medical_records'
  post 'my_patients/:patient_id/medical_records', to: 'medical_records#create', as: 'medical_record'

  resources :vacations, except: [:show]
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :integer          not null, primary key
#  level      :integer
#  lock       :boolean          default(FALSE)
#  name       :string           default("")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Department < ApplicationRecord
  include Defaultable
  include Activeable
  include Sortable
  include Toggleable
  include Statusable

  has_many :users

  validates :level, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 150 }

  scope :except_default, -> { where.not(name: 'default') }
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_hr

  def index
    @departments = Department.all.order_by(:level)
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new department_params
    if @department.save
      flash[:notice] = "Добавлен отдел #{@department.name}"
    else
      flash[:alert] = "Ошибка при добавлении отдела #{@department.name}"
    end
    redirect_to departments_path
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if @department.update department_params
      flash[:notice] = "Добавлен отдел #{@department.name}"
    else
      flash[:alert] = "Ошибка при обновлений должности #{@department.name}"
    end
    redirect_to departments_path
  end

  def destroy
    @department = Department.find(params[:id])
    if @department.delete
      flash[:notice] = "Удален отдел #{@department.name}"
    else
      flash[:alert] = "Ошибка при удалении отдела #{@department.name}"
    end
    redirect_to departments_path
  end

  def toggle
    @department = Department.find(params[:id])
    if @department.toggle!
      flash[:notice] = "Обновлен статус #{@department.name}"
    else
      flash[:alert] = "Ошибка при обновлении статуса #{@department.name}"
    end
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name, :level, :lock)
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.slim
tr class=("row #{department.lock ? 'disable' : ''}")
  td.row-item
    .flex.items-center= index + 1
  td.row-item
    .flex.items-center
      .ml-4
        .text-sm.font-medium.text-gray-900
          = department.level
  td.row-item
    .text-sm.text-gray-900= department.name
  td.row-item
    span.px-2.inline-flex.text-xs.leading-5.font-semibold.rounded-full.bg-green-100.text-green-800
      = department.status
  td.row-item.text-right.text-sm.font-medium
    = link_to toggle_department_path(department), method: :put, class: 'btn btn-green btn-outline mr-2', id: "department-toggle-#{department.id}" do
      i.fas.fa-toggle-on titile="Поменять статус"
    = link_to edit_department_path(department), class: 'btn btn-indigo btn-outline mr-2' do
      i.far.fa-edit title="Редактировать"
    = link_to department_path(department), method: :delete, class: 'btn btn-red btn-outline', id: "department-destroy-#{department.id}" do
      i.fas.fa-trash title="Удалить"

app/views/departments/_form.slim
= form_with(model: department) do |form|
  .input-group
    = form.label :level, class: 'label'
    = form.text_field :level, class: 'input', id: 'department-level'
  .input-group
    = form.label :name
    = form.text_field :name, class: 'input', id: 'department-name'  
  .mb-6.input-checkbox
    = form.check_box :lock
    = form.label :lock, class:"label"
  .input-group
    = form.submit class: 'btn btn-default', id: 'department-submit'

app/views/departments/edit.slim
.mt-8
  =render 'departments/form', department: @department

app/views/departments/index.slim
h1 Должность
.flex.flex-col.text-left.mt-10
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.table
          thead.head
            tr
              th.column scope="col" 
                | №
              th.column scope="col" 
                | Уровень
              th.column scope="col" 
                | Название
              th.column scope="col" 
                | Стаутс
              th.relative.px-6.py-3 scope="col" 
                span.sr-only Edit
          tbody.bg-white.divide-y.divide-gray-200
            - @departments.each_with_index do |department, index|
              = render 'departments/department', department: department, index: index

app/views/departments/new.slim
.mt-8
  =render 'departments/form', department: @department