config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :positions, except: [:show] do
    put :toggle, on: :member
  end
  resources :departments, except: [:show] do
    put :toggle, on: :member
  end
  resources :phones, except: [:show] do
    put :toggle, on: :member
  end
  resources :phonebooks, only: [:index]
  resources :patients, except: [:show, :destroy] do
    put :toggle, on: :member
  end
  get 'my_patients', to: 'patients#my_patients'
  get 'my_patients/:patient_id/testing', to: 'testings#go_to_test', as: 'go_to_testings'
  get 'my_patients/:patient_id/testing/history', to: 'testings#history', as: 'history_testings'
  get 'my_patients/:patient_id/testing/:test_id/new', to: 'testings#new', as: 'new_testings'
  post 'my_patients/:patient_id/testing', to: 'testings#create', as: 'testings'

  get 'my_patients/:patient_id/medical_records', to: 'medical_records#index', as: 'medical_records'
  get 'my_patients/:patient_id/medical_records/new', to: 'medical_records#new', as: 'new_medical_records'
  post 'my_patients/:patient_id/medical_records', to: 'medical_records#create', as: 'medical_record'

  resources :vacations, except: [:show]
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id                :integer          not null, primary key
#  document_number   :string           not null
#  first_name        :string           not null
#  last_name         :string           not null
#  lock              :boolean          not null
#  middle_name       :string           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  current_doctor_id :integer
#
# Indexes
#
#  index_patients_on_current_doctor_id  (current_doctor_id)
#
# Foreign Keys
#
#  current_doctor_id  (current_doctor_id => users.id)
#
class Patient < ApplicationRecord
  include Activeable
  include NameOfPerson
  include Sortable
  include Statusable

  belongs_to :current_doctor, class_name: 'User', foreign_key: 'current_doctor_id', optional: true

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :middle_name, presence: true, length: { maximum: 50 }
  validates :document_number, presence: true, length: { maximum: 50 }

  def name_of_current_doctor
    current_doctor.nil? ? '' : current_doctor.full_name
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_register, only: [:index, :new, :create, :edit, :update, :toggle]
  before_action :authenticate_doctor, only: [:my_patients]

  def index
    @patients = Patient.includes(:current_doctor).all.order_by(:lock)
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new patient_params
    if @patient.save
      flash[:notice] = "Добавлен пациент #{@patient.full_name}"
    else
      flash[:alert] = "Ошибка при добавлении пациента #{@patient.full_name}"
    end
    redirect_to patients_path
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update patient_params
      flash[:notice] = "Обновлены данные пациента #{@patient.full_name}"
    else
      flash[:alert] = "Ошибка при обновлении данных пациента #{@patient.full_name}"
    end
    redirect_to patients_path
  end

  def toggle
    @patient = Patient.find(params[:id])
    if @patient.toggle!
      flash[:notice] = "Заблкирован пациент #{@patient.full_name}"
    else
      flash[:alert] = "Ошибка при блoкировки пациента #{@patient.full_name}"
    end
    redirect_to patients_path
  end

  def my_patients
    @patients = Patient.includes(:current_doctor).where(current_doctor: current_user).enabled
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :middle_name, :document_number)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_patient.slim
div class=("card #{patient.lock ? 'bg-gray-200' : ''}")
  .card-content
    .card-title 
      | Номер карточки: 
      =patient.document_number
    .card-body
      p
        |ФИО: 
        =patient.full_name
      p
        |Статус: 
        =patient.status
      p
        |Текущий врач: 
        =patient.current_doctor.full_name
      -if current_user.doctor?
        .
          =link_to 'Провести тест', go_to_testings_path(patient.id), class: 'btn btn-indigo mr-5'
          =link_to 'История тестов', history_testings_path(patient), class: 'btn btn-indigo mr-5'
          =link_to 'Записи', medical_records_path(patient), class: 'btn btn-indigo mr-5'
          =link_to 'Добавить Записи', new_medical_records_path(patient), class: 'btn btn-indigo mr-5'

app/views/patients/_patient_row.slim
tr class=("row #{patient.lock ? 'disable' : ''}")
  td.row-item
    .flex.items-center= index + 1
  td.row-item
    .text-sm.text-gray-900 =patient.document_number
  td.row-item
      =patient.full_name
  td.row-item
    span.px-2.inline-flex.text-xs.leading-5.font-semibold.rounded-full.bg-green-100.text-green-800
      = patient.status
  td.row-item
    .text-sm.text-gray-900= patient.name_of_current_doctor

app/views/patients/index.slim
h2.text-center Список пациентов
hr
h2.text-center Форма поиска
hr

.flex.flex-col.text-left.mt-10
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.table
          thead.head
            tr
              th.column scope="col" 
                | №
              th.column scope="col" 
                | Номер документа
              th.column scope="col" 
                | ФИО
              th.column scope="col" 
                | Стаутс
              th.column scope="col" 
                | Доктор
              th.relative.px-6.py-3 scope="col" 
                span.sr-only Edit
          tbody.bg-white.divide-y.divide-gray-200
            - @patients.each_with_index do |patient, index|
              = render 'patients/patient_row', patient: patient, index: index

  

app/views/patients/my_patients.slim
h2 
  | Список пациентов доктора: 
  =current_user.full_name
hr
h2 Форма поиска
hr
=render @patients
  

app/views/patients/new.slim
h2.text-center Добавить пациента
hr

.w-2/4.mx-auto
 =form_with(model: @patient) do |form|
    .input-group
      =form.label :document_number, class: 'label'
      =form.text_field :document_number, class: 'input'

    .input-group
      =form.label :first_name, class: 'label'
      =form.text_field :first_name, class: 'input'

    .input-group
      =form.label :last_name, class: 'label'
      =form.text_field :last_name, class: 'input'

    .input-group
      =form.label :middle_name, class: 'label'
      =form.text_field :middle_name, class: 'input'

    .input-group
      =form.submit "Добавить", class: "btn btn-default"