config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :positions, except: [:show] do
    put :toggle, on: :member
  end
  resources :departments, except: [:show] do
    put :toggle, on: :member
  end
  resources :phones, except: [:show] do
    put :toggle, on: :member
  end
  resources :phonebooks, only: [:index]
  resources :patients, except: [:show, :destroy] do
    put :toggle, on: :member
  end
  get 'my_patients', to: 'patients#my_patients'
  get 'my_patients/:patient_id/testing', to: 'testings#go_to_test', as: 'go_to_testings'
  get 'my_patients/:patient_id/testing/history', to: 'testings#history', as: 'history_testings'
  get 'my_patients/:patient_id/testing/:test_id/new', to: 'testings#new', as: 'new_testings'
  post 'my_patients/:patient_id/testing', to: 'testings#create', as: 'testings'

  get 'my_patients/:patient_id/medical_records', to: 'medical_records#index', as: 'medical_records'
  get 'my_patients/:patient_id/medical_records/new', to: 'medical_records#new', as: 'new_medical_records'
  post 'my_patients/:patient_id/medical_records', to: 'medical_records#create', as: 'medical_record'

  resources :vacations, except: [:show]
end

app/views/layouts/_navbar.slim
nav.bg-white.shadow.dark:bg-gray-800
  .container.px-6.py-3.mx-auto.md:flex.md:justify-between.md:items-center
    .flex.items-center.justify-between
      div
        =link_to 'Tester', root_path, class: "text-xl font-bold text-gray-800 dark:text-white md:text-2xl hover:text-gray-700 dark:hover:text-gray-300"
      - if user_signed_in?    
        =link_to 'Телефонная книга', phonebooks_path, class: "rounded-t ml-5"
        - if current_user.register?
          =link_to 'Пациенты', patients_path, class: "rounded-t ml-5"
          =link_to 'Добавить пациента', new_patient_path, class: "rounded-t ml-5"
        - if current_user.doctor?
          =link_to 'Мои Пациенты', my_patients_path, class: "rounded-t ml-5"
        - if current_user.hr?
          =link_to 'Отпуска', vacations_path, class: "rounded-t ml-5"
        
    - if user_signed_in?
      .items-center.md:flex data-controller="dropdown"
        .dropdown.inline-block.relative
          button.bg-gray-300.text-gray-700.font-semibold.py-2.px-4.rounded.inline-flex.items-center data-action="click->dropdown#toggle"
            span.mr-1 =current_user.abbreviated
            svg.fill-current.h-4.w-4 viewbox=("0 0 20 20") xmlns="http://www.w3.org/2000/svg" 
              path d=("M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z") 
          ul.dropdown-menu.absolute.hidden.text-gray-700.pt-1  data-dropdown-target="toggleable"
            - if current_user.admin_or_hr?
              li
                =link_to 'Должности', positions_path, class: "rounded-t bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
            li
              =link_to 'Выйти', destroy_user_session_path, method: :delete, class: "rounded-t bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
    - else
      .flex.justify-center.md:block
        = link_to new_user_session_path, class: 'relative.text-gray-700.dark:text-gray-200.hover:text-gray-600.dark:hover:text-gray-300' do
          button.btn.btn-green.btn-outline Войти
          span.absolute.top-0.left-0.p-1.text-xs.text-white.bg-indigo-500.rounded-full
          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tester</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mx-auto">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>